### ISSUE TITLE
Exception with example from README

### ISSUE THREAD

**Issue by ralfstx** [statisticsnorway/java-vtl#26]
Running the example from the [README.md](https://github.com/statisticsnorway/java-vtl/blob/develop/README.md) leads to the following exception:

> Exception in thread "main" no.ssb.vtl.script.error.SyntaxException: mismatched input 'sum' expecting {'rename', 'IDENTIFIER', 'MEASURE', 'ATTRIBUTE', 'filter', 'keep', 'fold', 'unfold', 'drop', IDENTIFIER}

Using a different name works. I'm not sure if `sum` is a reserved keyword or if that's an issue with the parser.

**Comment by hadrienk** [comment]
Hi Ralf. Thank you for taking the time to report this.

Sum is indeed a reserved word, the example was written at a time the sum function was not implemented yet. I will update the README.md

Hadrien
