### ISSUE TITLE
Eval() for lots of arithmetic expressions slow

### ISSUE THREAD

**Issue by pawbu** [statisticsnorway/java-vtl#70]
This is a follow-up of https://github.com/statisticsnorway/java-vtl/pull/68.
There are some tests for evaluating arithmetic expressions in `VTLScriptEngineAdvancedTest` class that are marked as ignored. This is not the case with the division operator (`/`) which seems strange.

**Comment by hadrienk** [comment]
Are `*`, `+` and `-` having the same performance issues? Could be that @takvamborgen forgot to remove the ignore annotation?

**Comment by pawbu** [comment]
I don't now what kind of machine you have, but on my underpowered i7-6500U these tests fail ;D

**Comment by hadrienk** [comment]
Haha, yeah no it does not work. The JIT is not caching up the getVTLType() calls. Pushing a simple fix now.
